# Ruby CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_PATH: vendor/bundle
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_DB: circleci_initial_test
          MYSQL_PASSWORD: ''
    working_directory: ~/circleci-initial
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - docker-cache-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: docker-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database create
          command: bin/rails db:create
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

workflows:
  version: 2
  step:
    jobs:
      - test
