# Ruby CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_PATH: vendor/bundle
          DB_HOST: 127.0.0.1
           DB_USERNAME: 'root'
           DB_PASSWORD: ''
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_DB: circleci_initial_test
          MYSQL_PASSWORD: ''
    working_directory: ~/circleci-initial
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - docker-cache-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: docker-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3307 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

      - save_cache:
            - docker-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            -  ~/caches/app.tar
